(() => {
 'use strict';
 const d=window.OBSERVATORY_FINANCE,es=window.OBSERVATORY_LOCALE!=='en',lang=es?'es':'en',t=(a,b)=>es?a:b;
 const countryNames=new Intl.DisplayNames([lang],{type:"region"}),iso2={"ARG": "AR", "BHS": "BS", "BRB": "BB", "BLZ": "BZ", "BOL": "BO", "BRA": "BR", "CHL": "CL", "COL": "CO", "CRI": "CR", "DOM": "DO", "ECU": "EC", "SLV": "SV", "GTM": "GT", "GUY": "GY", "HTI": "HT", "HND": "HN", "JAM": "JM", "MEX": "MX", "NIC": "NI", "PAN": "PA", "PRY": "PY", "PER": "PE", "SUR": "SR", "TTO": "TT", "URY": "UY", "VEN": "VE"};
 const countryName=iso=>countryNames.of(iso2[iso]);
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const names=[...new Map(d.observations.map(r=>[r.iso3,r.country])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
 const section=document.createElement('section');section.className='lac-evidence';section.id='education-finance';
 section.innerHTML=`<p class="eyebrow">UNESCO UIS · ${t('BANCO MUNDIAL','WORLD BANK')}</p><h2>${t('Cómo evoluciona el gasto público en educación','How public education expenditure evolves')}</h2><p>${t('Series oficiales para 26 países de América Latina y el Caribe, 2000–2025; disponibilidad variable. Fuente UNESCO UIS, consultada mediante la API del Banco Mundial.','Official series for 26 Latin American and Caribbean countries, 2000–2025; availability varies. UNESCO UIS data retrieved through the World Bank API.')}</p><div class="cima-filters"><label>${t('País','Country')} <select id="finance-country">${names.map(([iso,name])=>`<option value="${iso}">${esc(countryName(iso))}</option>`).join('')}</select></label><label>${t('Indicador','Indicator')} <select id="finance-metric">${d.metrics.map(m=>`<option value="${m.id}">${esc(m[lang])}</option>`).join('')}</select></label></div><p id="finance-status" role="status"></p><div class="table-scroll"><table class="teacher-table"><thead><tr><th>${t('Año','Year')}</th><th>${t('Valor (%)','Value (%)')}</th><th>${t('Fuente oficial','Official source')}</th></tr></thead><tbody id="finance-rows"></tbody></table></div><p class="evidence-limit">${t('— significa dato no disponible, nunca cero. Son medidas del gasto público total en educación; no representan inversión exclusiva en IA ni separan gasto corriente e inversión de capital. Un aumento del porcentaje del PIB puede deberse a cambios en el gasto o en el PIB. Estas series no demuestran causalidad sobre los aprendizajes.','— means unavailable, never zero. These measures cover total public education expenditure; they do not represent AI-specific investment or separate current spending from capital investment. A higher share of GDP may reflect changes in spending or GDP. These series do not establish causal effects on learning.')}</p><p><a href="${es?'':'../'}data/education-finance.json">${t('Descargar series y trazabilidad API (JSON)','Download series and API provenance (JSON)')}</a> · <a href="https://data.worldbank.org/indicator/SE.XPD.TOTL.GD.ZS">${t('Consultar fuente y metodología','View source and methodology')} ↗</a> · <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a></p><p class="evidence-caption">${t('Fecha de consulta','Retrieval date')}: ${esc(d.retrieved_at.slice(0,10))}. ${t('Instantánea validada; no consulta en tiempo real. Los datos CIMA y estas series tienen procedencias y coberturas distintas.','Validated snapshot; not a real-time query. CIMA data and these series have different provenance and coverage.')}</p>`;
 document.getElementById('cima-context').after(section);
 function render(){const rows=d.observations.filter(r=>r.iso3===section.querySelector('#finance-country').value&&r.metric_id===section.querySelector('#finance-metric').value).sort((a,b)=>b.year-a.year);const count=rows.filter(r=>r.value!==null).length;section.querySelector('#finance-status').textContent=count+' '+t('años con datos; se muestran también las ausencias','years with data; missing values are also shown');section.querySelector('#finance-rows').innerHTML=rows.map(r=>`<tr><th scope="row">${r.year}</th><td>${r.value===null?'—':r.value.toLocaleString(lang,{maximumFractionDigits:2})}</td><td><a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">UIS / WDI ↗</a></td></tr>`).join('');}
 section.querySelectorAll('select').forEach(s=>s.addEventListener('change',render));render();
})();
